# Generated by Django 3.0.6 on 2020-05-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20200526_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photoimage',
            name='location',
            field=models.ManyToManyField(to='picture.Location'),
        ),
    ]
