# Generated by Django 3.0.6 on 2020-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20200526_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoimage',
            name='location',
            field=models.ManyToManyField(to='picture.Location'),
        ),
    ]
