# Generated by Django 3.0.6 on 2020-05-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20200527_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoimage',
            name='location',
        ),
        migrations.AddField(
            model_name='photoimage',
            name='location',
            field=models.ForeignKey(default=1,on_delete=django.db.models.deletion.DO_NOTHING, to='picture.Location'),
            preserve_default=False,
        ),
    ]
